Include the missing `bin` argument parsing logic
massalabs/massa-sc-scripts pull request #2
Opened 2022-03-18 09:51 UTC by yvan-sraka

Fix #1

2022-03-18 18:47 UTC, qdrn commented
As of now it does not work in combination with the `massa-sc-template`. See https://github.com/massalabs/massa-sc-template/pull/10

2022-03-18 18:47 UTC, qdrn requested changes

2022-03-18 18:47 UTC, qdrn commented on index.js
> +                `asc src/${argv.path} --target release --exportRuntime --binaryFile build/${argv.path}`
```js
`asc src/${argv.path} --target release --exportRuntime --binaryFile build/${argv.path}`
```
It would be nicer to export the file with the `.wasm` extension.

2022-04-01 09:42 UTC, Eitu33 approved these changes

2022-04-04 07:58 UTC, qdrn approved these changes

2022-04-04 07:58 UTC, merged